"""add human_reviews table

Revision ID: 4641816aa058
Revises: e497f0dddb47
Create Date: 2026-07-10 04:11:28.305147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4641816aa058'
down_revision: Union[str, Sequence[str], None] = 'e497f0dddb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reviewed_paper_id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id_display', sa.String(length=128), nullable=True),
    sa.Column('paper_title', sa.Text(), nullable=True),
    sa.Column('venue', sa.Enum('miccai', 'bmvc', 'neurips', 'ijcb', 'cvpr', 'other', name='venue'), nullable=True),
    sa.Column('venue_other', sa.String(length=128), nullable=True),
    sa.Column('reviewer_name', sa.String(length=128), nullable=True),
    sa.Column('conflict_of_interest', sa.Enum('none', 'declared', name='conflictofinterest'), nullable=True),
    sa.Column('reviewer_expertise', sa.Enum('expert', 'knowledgeable', 'passing_familiarity', name='reviewerexpertise'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses_major', sa.JSON(), nullable=True),
    sa.Column('weaknesses_minor', sa.JSON(), nullable=True),
    sa.Column('questions_for_rebuttal', sa.JSON(), nullable=True),
    sa.Column('final_conclusion', sa.Text(), nullable=True),
    sa.Column('rating', sa.Enum('reject', 'weak_reject', 'borderline_reject', 'borderline_accept', 'weak_accept', 'accept', name='humanreviewrating'), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('rating_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_paper_id'], ['reviewed_papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewed_paper_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('human_reviews')
    # ### end Alembic commands ###
