"""initial schema

Revision ID: e497f0dddb47
Revises: 
Create Date: 2026-07-08 13:20:44.064988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e497f0dddb47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('arxiv', 'semantic_scholar', 'peerread', name='papersource'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external')
    )
    op.create_table('reviewed_papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('uploaded_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'awaiting_approval', 'completed', 'failed', name='reviewedpaperstatus'), nullable=False),
    sa.Column('parsed_title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('faiss_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('section_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('active', 'stale', 'deleted', name='chunkstatus'), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_faiss_id', 'chunks', ['faiss_id'], unique=False)
    op.create_index('idx_status', 'chunks', ['status'], unique=False)
    op.create_table('human_approvals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reviewed_paper_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'revise', 'reject', name='approvaldecision'), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_paper_id'], ['reviewed_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflection_flags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reviewed_paper_id', sa.BigInteger(), nullable=False),
    sa.Column('flagged_agent', sa.String(length=64), nullable=False),
    sa.Column('issue_text', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_paper_id'], ['reviewed_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_assessments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reviewed_paper_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('revision_pass', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_paper_id'], ['reviewed_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviewed_paper', 'review_assessments', ['reviewed_paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviewed_paper', table_name='review_assessments')
    op.drop_table('review_assessments')
    op.drop_table('reflection_flags')
    op.drop_table('human_approvals')
    op.drop_index('idx_status', table_name='chunks')
    op.drop_index('idx_faiss_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('reviewed_papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
